# Permalinks
permalink:        pretty

# Setup
title:            Jacques Thurling
tagline:          'Full-Stack Software Developer'
description:      ''
url:              jacquesthurling.com
baseurl:          /

author:
  name:           ''
  url:            

paginate:         5
paginate_path:    "page:num"
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Gl4SS3S
