# Permalinks
permalink:        pretty

# Setup
title:            Jacques Thurling
tagline:          'Full-Stack Software Developer'
description:      ''
url:              https://www.jacquesthurling.com
baseurl:          /

author:
  name:           'Jacques Thurling'
  url:            

paginate:         5
paginate_path:    "page:num"
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
# Custom vars
version:          2.1.0
google_analytics: "G-J7LPSHLPY6"


github:
  repo:           https://github.com/Gl4SS3S
